Alternative II: use RiskyValue/SafeValue
Timing-GmbH/SQLite.swift pull request #4
Opened 2020-12-16 10:45 UTC by DivineDominion

The last commit #1fd1b18  eventually made Timing's `Optional<T>` conformance to syncable data types possible again. This led to the result looking way too similar to #3 for what I set out to achieve.

I still like the naming better and would prefer this PR over #3, so: 

Closes #3

WDYT?

2020-12-16 11:29 UTC, MrMage requested changes
Looks indeed "nicer" than the other option :-)

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-:-MOfIuo-38VOR_iXGVy3:blypqi6)* status: all files reviewed, 4 unresolved discussions (waiting on @DivineDominion)

___
*[Sources/SQLite/Foundation.swift, line 74 at r1](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-MOfI4uGCVXD2UiAVxea:-MOfI4uGCVXD2UiAVxeb:b-yb3zz4) ([raw file](https://github.com/mrmage/sqlite.swift/blob/1fd1b182964ca87a8108b479883493516ec95da8/Sources/SQLite/Foundation.swift#L74)):*
> ```Swift
> extension URL : RiskyValue {
>     
>     public struct URLRiskyValueError: Error {}
> ```

Make this an enum?
___
*[Sources/SQLite/Core/Value.swift, line 26 at r1](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-MOfIFeHDgk9JqpeZFph:-MOfIFeHDgk9JqpeZFpi:b-u5cppx) ([raw file](https://github.com/mrmage/sqlite.swift/blob/1fd1b182964ca87a8108b479883493516ec95da8/Sources/SQLite/Core/Value.swift#L26)):*
> ```Swift
> 
> /// Introduces `fromDatatypeValue` in a shared way into `SafeValue` and `RiskyValue`.
> public protocol Datatyped {
> ```

What's the motivation for this? (Maybe update the comment to make that more clear?)
___
*[Sources/SQLite/Typed/Operators.swift, line 524 at r1](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-MOfIWaZAPMxzAXYDFZz:-MOfIWaZAPMxzAXYDF_-:b-l9u11l) ([raw file](https://github.com/mrmage/sqlite.swift/blob/1fd1b182964ca87a8108b479883493516ec95da8/Sources/SQLite/Typed/Operators.swift#L524)):*
> ```Swift
> }
> 
> public func ~=<V : Value>(lhs: PartialRangeThrough<V>, rhs: Expression<V>) -> Expression<Bool> where V.Datatype : Comparable & SafeValue {
> ```

Why would this not work with any `Value`? (Possibly also elsewhere)
___
*[Tests/SQLiteTests/FoundationTests.swift, line 17 at r1](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-MOfIsxY7a-irDMkeSv_:-MOfIsxY7a-irDMkeSva:b-uxqb62) ([raw file](https://github.com/mrmage/sqlite.swift/blob/1fd1b182964ca87a8108b479883493516ec95da8/Tests/SQLiteTests/FoundationTests.swift#L17)):*
> ```Swift
>     }
> 
>     func testStringToURL() throws {
> ```

Do you think it would also make sense to test this with an actual DB table? (Could also do that in the Timing codebase instead.)


<!-- Sent from Reviewable.io -->

2020-12-16 16:38 UTC, DivineDominion reviewed
> *[Reviewable](https://reviewable.io/reviews/mrmage/sqlite.swift/4)* status: all files reviewed, 4 unresolved discussions (waiting on @MrMage)

___
*[Sources/SQLite/Foundation.swift, line 74 at r1](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-MOfI4uGCVXD2UiAVxea:-MOg5n6P5EjGel5bvwwP:b-896fix) ([raw file](https://github.com/mrmage/sqlite.swift/blob/1fd1b182964ca87a8108b479883493516ec95da8/Sources/SQLite/Foundation.swift#L74)):*
<details><summary><i>Previously, MrMage (Daniel Alm) wrote…</i></summary><blockquote>

Make this an enum?
</blockquote></details>

Done.
___
*[Sources/SQLite/Core/Value.swift, line 26 at r1](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-MOfIFeHDgk9JqpeZFph:-MOg4yR27EJohQOOoR_d:b-ef2owd) ([raw file](https://github.com/mrmage/sqlite.swift/blob/1fd1b182964ca87a8108b479883493516ec95da8/Sources/SQLite/Core/Value.swift#L26)):*
<details><summary><i>Previously, MrMage (Daniel Alm) wrote…</i></summary><blockquote>

What's the motivation for this? (Maybe update the comment to make that more clear?)
</blockquote></details>

We can get by without it completely.

For context: I started with this only containing the `fromDatatypeValue` method and wanted to limit Row.get etc. to this -- but I had to move more and more over to make things work in the app.
___
*[Sources/SQLite/Typed/Operators.swift, line 524 at r1](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-MOfIWaZAPMxzAXYDFZz:-MOg60hDAwzH2uK3wB3k:bcpkc5s) ([raw file](https://github.com/mrmage/sqlite.swift/blob/1fd1b182964ca87a8108b479883493516ec95da8/Sources/SQLite/Typed/Operators.swift#L524)):*
<details><summary><i>Previously, MrMage (Daniel Alm) wrote…</i></summary><blockquote>

Why would this not work with any `Value`? (Possibly also elsewhere)
</blockquote></details>

Mostly an oversight from the name changes, really, that I didn't notice in the diff during the back-and-forth. Fixed!
___
*[Tests/SQLiteTests/FoundationTests.swift, line 17 at r1](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-MOfIsxY7a-irDMkeSv_:-MOgDvZP9ESVPXpm8Z7V:bsmfon0) ([raw file](https://github.com/mrmage/sqlite.swift/blob/1fd1b182964ca87a8108b479883493516ec95da8/Tests/SQLiteTests/FoundationTests.swift#L17)):*
<details><summary><i>Previously, MrMage (Daniel Alm) wrote…</i></summary><blockquote>

Do you think it would also make sense to test this with an actual DB table? (Could also do that in the Timing codebase instead.)
</blockquote></details>

Done! The "integration" tests we have inside this lib are few. But I think it makes sense to check it here, too, and not just in Timing to demonstrate the API. (I think SQLite.swift is weird enough as-is tbh :))


<!-- Sent from Reviewable.io -->

2020-12-17 09:13 UTC, MrMage requested changes
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mrmage/sqlite.swift/4)* status: all files reviewed, 4 unresolved discussions (waiting on @DivineDominion)

___
*[Sources/SQLite/Typed/CustomFunctions.swift, line 42 at r2](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-MOjyGQy6my6EbCTRY5j:-MOjyGQy6my6EbCTRY5k:b-82oa9d) ([raw file](https://github.com/mrmage/sqlite.swift/blob/8b0d5daf142ed810541bac5fbe3b9866811cc082/Sources/SQLite/Typed/CustomFunctions.swift#L42)):*
> ```Swift
>     ///
>     /// - Returns: A closure returning an SQL expression to call the function.
>     func createFunction<Z : SafeValue>(_ function: String, deterministic: Bool = false, _ block: @escaping () -> Z) throws -> (() -> Expression<Z>) {
> ```

Can these also be reverted to `Value`? (If not, just let me know.)
___
*[Sources/SQLite/Typed/Expression.swift, line 146 at r2](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-MOjyLwG6sjWEEkKhcC_:-MOjyLwG6sjWEEkKhcCa:b-82oa9d) ([raw file](https://github.com/mrmage/sqlite.swift/blob/8b0d5daf142ed810541bac5fbe3b9866811cc082/Sources/SQLite/Typed/Expression.swift#L146)):*
> ```Swift
> public let rowid = Expression<Int64>("ROWID")
> 
> public func cast<T: SafeValue, U: SafeValue>(_ expression: Expression<T>) -> Expression<U> {
> ```

Can these also be reverted to `Value`? (If not, just let me know.)
___
*[Sources/SQLite/Typed/Operators.swift, line 107 at r2](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-MOjyMic9nT3IOtYPTWq:-MOjyMic9nT3IOtYPTWr:b-82oa9d) ([raw file](https://github.com/mrmage/sqlite.swift/blob/8b0d5daf142ed810541bac5fbe3b9866811cc082/Sources/SQLite/Typed/Operators.swift#L107)):*
> ```Swift
>     return Operator.plus.infix(lhs, rhs)
> }
> public func +<V: SafeValue>(lhs: V, rhs: Expression<V?>) -> Expression<V?> where V.Datatype : Number {
> ```

Can these also be reverted to `Value`? (If not, just let me know.)
___
*[Sources/SQLite/Typed/Query.swift, line 982 at r2](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-MOjyPNUAWPoLOchHevP:-MOjyPNUAWPoLOchHevQ:b-82oa9d) ([raw file](https://github.com/mrmage/sqlite.swift/blob/8b0d5daf142ed810541bac5fbe3b9866811cc082/Sources/SQLite/Typed/Query.swift#L982)):*
> ```Swift
>     }
> 
>     public func scalar<V : SafeValue>(_ query: ScalarQuery<V>) throws -> V {
> ```

Can these also be reverted to `Value`? (If not, just let me know.)


<!-- Sent from Reviewable.io -->

2020-12-17 14:18 UTC, DivineDominion reviewed
+reviewer:@mrmage Sorry for the overlooked pieces. My attention is apparently split worse this week than anticipated. Will try to come up with 2nd passes of checks before submitting.

> *[Reviewable](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-:-MOl36ro1pFhaPaL7QkD:b-kxt4xo)* status: all files reviewed, 4 unresolved discussions (waiting on @MrMage)

___
*[Sources/SQLite/Typed/CustomFunctions.swift, line 42 at r2](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-MOjyGQy6my6EbCTRY5j:-MOkzc7h0JVsKrq7gYq9:b-hnxxjo) ([raw file](https://github.com/mrmage/sqlite.swift/blob/8b0d5daf142ed810541bac5fbe3b9866811cc082/Sources/SQLite/Typed/CustomFunctions.swift#L42)):*
<details><summary><i>Previously, MrMage (Daniel Alm) wrote…</i></summary><blockquote>

Can these also be reverted to `Value`? (If not, just let me know.)
</blockquote></details>

I don't think so.

This requires the `value` helper to be throwing, which is doable. But then all the `createFunction` variants need to support throwing, and the actual implementation in `Connection.createFunction` uses the `Function` typealias:

```
 fileprivate typealias Function = @convention(block) (OpaquePointer?, Int32, UnsafeMutablePointer<OpaquePointer?>?) -> Void

```

... which also would have to become throwing then. But it's Obj-C block convention / C compatibility prevents that.
___
*[Sources/SQLite/Typed/Expression.swift, line 146 at r2](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-MOjyLwG6sjWEEkKhcC_:-MOl0zn309Ur3ljIgvKD:b-qy3qc7) ([raw file](https://github.com/mrmage/sqlite.swift/blob/8b0d5daf142ed810541bac5fbe3b9866811cc082/Sources/SQLite/Typed/Expression.swift#L146)):*
<details><summary><i>Previously, MrMage (Daniel Alm) wrote…</i></summary><blockquote>

Can these also be reverted to `Value`? (If not, just let me know.)
</blockquote></details>

yes, done!
___
*[Sources/SQLite/Typed/Operators.swift, line 107 at r2](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-MOjyMic9nT3IOtYPTWq:-MOl1MS89W1d4gV2z4TQ:bcfr2ss) ([raw file](https://github.com/mrmage/sqlite.swift/blob/8b0d5daf142ed810541bac5fbe3b9866811cc082/Sources/SQLite/Typed/Operators.swift#L107)):*
<details><summary><i>Previously, MrMage (Daniel Alm) wrote…</i></summary><blockquote>

Can these also be reverted to `Value`? (If not, just let me know.)
</blockquote></details>

Yes. Sorry, my regex failed because of the space. Should've double-checked. Will try to pay closer attention to the PRs this week :bow: 
___
*[Sources/SQLite/Typed/Query.swift, line 982 at r2](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-MOjyPNUAWPoLOchHevP:-MOl2cCG7Q5j6fvBRvr8:b-acx4ve) ([raw file](https://github.com/mrmage/sqlite.swift/blob/8b0d5daf142ed810541bac5fbe3b9866811cc082/Sources/SQLite/Typed/Query.swift#L982)):*
<details><summary><i>Previously, MrMage (Daniel Alm) wrote…</i></summary><blockquote>

Can these also be reverted to `Value`? (If not, just let me know.)
</blockquote></details>

I'm torn on these!

I was able to change the type to `Value`. But I'm not quite sure if the reason for failure here is "semantically different" from the failure reason from the throwing `scalar` functions that we had before. Thankfully, this stuff that is client-facing, so we can figure out the error reason in the app if we stumble into problems. So we're safe in practice, I think.


<!-- Sent from Reviewable.io -->

2020-12-17 14:58 UTC, MrMage requested changes
Looks good, we are almost done!

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-:-MOlCNV26ap8FH_EHmbx:b-zdm4mv)* status: all files reviewed, 1 unresolved discussion (waiting on @DivineDominion)

___
*[Sources/SQLite/Helpers.swift, line 141 at r3](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-MOlBxHxEhdDtpwb0Fzq:-MOlBxHxEhdDtpwb0Fzr:bbsn6ge) ([raw file](https://github.com/mrmage/sqlite.swift/blob/7227317038d93774886601bf78d06fac15d365a4/Sources/SQLite/Helpers.swift#L141)):*
> ```Swift
> }
> 
> func throwingValue<A: Value>(_ v: Binding?) throws -> A {
> ```

Is the method with the optional argument needed? Should we maybe make it throw instead of crash if the argument is `nil`?


<!-- Sent from Reviewable.io -->

2020-12-17 15:22 UTC, DivineDominion reviewed
> *[Reviewable](https://reviewable.io/reviews/mrmage/sqlite.swift/4)* status: all files reviewed, 1 unresolved discussion (waiting on @MrMage)

___
*[Sources/SQLite/Helpers.swift, line 141 at r3](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-MOlBxHxEhdDtpwb0Fzq:-MOlHT8s-KKBjMqHO0VO:b-tnol0e) ([raw file](https://github.com/mrmage/sqlite.swift/blob/7227317038d93774886601bf78d06fac15d365a4/Sources/SQLite/Helpers.swift#L141)):*
<details><summary><i>Previously, MrMage (Daniel Alm) wrote…</i></summary><blockquote>

Is the method with the optional argument needed? Should we maybe make it throw instead of crash if the argument is `nil`?
</blockquote></details>

I think no: That's original code from Stephen Celis from 2015, btw, and making this throw escalates up through `createFunction` and eventually produces the same problem with the Swift-to-C block conversion ;(


<!-- Sent from Reviewable.io -->

2020-12-18 13:46 UTC, DivineDominion reviewed
+reviewer:@mrmage 

> *[Reviewable](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-:-MOq5QG77ql5rg-60klo:b44qd4o)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @MrMage)

___
*[Sources/SQLite/Helpers.swift, line 141 at r3](https://reviewable.io/reviews/mrmage/sqlite.swift/4#-MOlBxHxEhdDtpwb0Fzq:-MOq5HgK50ZgHTxdvDZ_:b1y2ufi) ([raw file](https://github.com/mrmage/sqlite.swift/blob/7227317038d93774886601bf78d06fac15d365a4/Sources/SQLite/Helpers.swift#L141)):*
<details><summary><i>Previously, DivineDominion (Christian Tietze) wrote…</i></summary><blockquote>

I think no: That's original code from Stephen Celis from 2015, btw, and making this throw escalates up through `createFunction` and eventually produces the same problem with the Swift-to-C block conversion ;(
</blockquote></details>

(Correction after ⌘R refresh)

I went ahead and replaced all 3 force casts in the `throwingValue` department.


<!-- Sent from Reviewable.io -->

2020-12-18 13:56 UTC, MrMage approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mrmage/sqlite.swift/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DivineDominion)



<!-- Sent from Reviewable.io -->

2020-12-18 14:01 UTC, merged